# Generated by Django 5.0.7 on 2024-07-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_string', models.TextField()),
                ('ast_json', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('age', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('experience', models.IntegerField()),
            ],
        ),
    ]
